apiVersion: v1
kind: Service
metadata:
  name: work-boots-api
  namespace: work-boots
spec:
  selector:
    app: work-boots-api
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
